// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkHPeChVP14JBo_Ykgb7r-htSUP-mK9CA',
    appId: '1:331595064262:web:5c8a4ef24601ef00fe48c7',
    messagingSenderId: '331595064262',
    projectId: 'quanlydaotao-46f1c',
    authDomain: 'quanlydaotao-46f1c.firebaseapp.com',
    databaseURL: 'https://quanlydaotao-46f1c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlydaotao-46f1c.appspot.com',
    measurementId: 'G-MKQNZYK4W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDES-LS2UDnhq9thWsyvO-O52ZyNCqCRIc',
    appId: '1:331595064262:android:1b20b4f75f7d1ffbfe48c7',
    messagingSenderId: '331595064262',
    projectId: 'quanlydaotao-46f1c',
    databaseURL: 'https://quanlydaotao-46f1c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlydaotao-46f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBofT9IcRcEGMa4HG623vzvhi9JN0x6YxM',
    appId: '1:331595064262:ios:04931b09305ba25dfe48c7',
    messagingSenderId: '331595064262',
    projectId: 'quanlydaotao-46f1c',
    databaseURL: 'https://quanlydaotao-46f1c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlydaotao-46f1c.appspot.com',
    iosBundleId: 'com.example.internshipmigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBofT9IcRcEGMa4HG623vzvhi9JN0x6YxM',
    appId: '1:331595064262:ios:e5ebedeb93d19cf2fe48c7',
    messagingSenderId: '331595064262',
    projectId: 'quanlydaotao-46f1c',
    databaseURL: 'https://quanlydaotao-46f1c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlydaotao-46f1c.appspot.com',
    iosBundleId: 'com.example.internshipmigi.RunnerTests',
  );
}
